#! /usr/bin/env bash

# To have access to an X-Server under Jupyter
export WSL2_GUI_APPS_ENABLED=1
export DISPLAY=:0
export XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
export WAYLAND_DISPLAY=wayland-0
export PULSE_SERVER=/mnt/wslg/pulseserver

# To make Jupyter configs live in Windows space
export JUPYTER_CONFIG_DIR=/home/ubuntu/.jupyter
export JUPYTER_CONFIG_PATH=/home/ubuntu/.jupyter

source /home/ubuntu/py311/bin/activate

# To prevent double-running
cd ~/repos
screen -wipe >/dev/null 2>&1
if ! screen -list | grep -q "jupyter"; then
    screen -dmS jupyter /home/ubuntu/pyenv/bin/jupyter lab --ip 0.0.0.0 --port 8888 --no-browser --ServerApp.password='argon2:$argon2id$v=19$m=10240,t=10,p=8$ijPab+qx2WAOlDKJiRE56Q$wJ5s4RI9dIw36HxHh+0P6eN8SwqTGy0PmnGe7D+oPlc'
fi
